allowBuilds:
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - '@types/leaflet@1.9.22'
patchedDependencies:
  react-leaflet@5.0.0: patches/react-leaflet@5.0.0.patch
